baseURL = "https://rkpblog.tech/"
languageCode = "en-us"
title = "Rohith's Blog"
theme = "hugo-ink"
enableEmoji = true
footnoteReturnLinkContents = "â†©"
enableGitInfo = true
googleAnalytics = "UA-163890179-2"
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
RelativeURLs=true
CanonifyURLs=true

copyright = "Â© Copyright notice"
disqusShortname = "rkpblog"

[params]
  AuthorName = "Rohith Palakirti"
  GitHubUser = "kprohith"
  Subtitle = "I'm Rohith Palakirti, currently a sophomore at Manipal Academy of Higher Education pursuing a Bachelor of Science in Computer Science. Skilled in Python, C++, Java, HTML, CSS, JavaScript. Pytorch, tensorflow, keras, Microsoft Azure, fast.ai and love tinkering with Arduinos. Interested in deep learning, neural networks and full-stack development. Always looking for opportunities to learn and improve.â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€ â€â€â€â€  â€â€â€ğŸ“§Email me at rohith [at] rkpblog [dot] tech"
  mode = "dark"
  featherIconsCDN = true
  disableDisqusTypes = ["page"]
[permalinks]
  posts = "/:year/:month/:title/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/kprohith"

[[params.social]]
icon = "linkedin"
icon_pack = "linkedin"
url = "https://linkedin.com/in/rohith-kp"

[[params.social]]
icon = "twitter"
icon_pack = "fa"
url = "https://twitter.com/fortytwochars"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"


[taxonomies]
   tag = "tags"


[frontmatter]
date = ":filename"